name: gptConversionApp -- Secrets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name : Access Secrets
        run: |
          echo "OPENAI KEYS : ${{secrets.OPENAI_API_KEYS}}"
          echo "PAPAGO_CLIENT_ID : ${{secrets.PAPAGO_CLIENT_ID}}"
          echo "PAPAGO_CLIENT_SECRET : ${{secrets.PAPAGO_CLIENT_SECRET}}"
